name: HugeLanskoy
version: '${project.version}'
main: me.zqr0.hugelanskoy.Plugin
api-version: 1.19
authors: [ ZQR0 ]
website: https://zqr0.github.io/Website/

commands:
  getAuthor:
    aliases:
      - ga
      - getAuthor
    usage: /ga

  lanskoy:
    aliases:
      - lnsk
    usage: /lnsk

  setgamemode:
    aliases:
      - sg
    usage: /sg < creative | survival >
